### ISSUE TITLE
Issue while building the project

### ISSUE THREAD

**Issue by sameepsi** [WorldwideAntimalarialResistanceNetwork/WWARN-Maps-Surveyor#77]
Hi,
I am getting this error while building the project. I am new to Maven, so please help
Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.6.3:run (default-cli) on project maps-surveyor-parent: For all packaging other than war you need to configure the container you wish to use.
Command I am executing-:
mvn -e clean verify org.codehaus.cargo:cargo-maven2-plugin:run

**Comment by nigel-v-thomas** [comment]
Hi sameepsi,
If you cd into SurveyorSimpleDemoApp directory, then run 
mvn -e clean verify org.codehaus.cargo:cargo-maven2-plugin:run
It should build and you can view the outcome at:
http://localhost:8080/SurveyorSimpleDemoApp-1.3.1-SNAPSHOT
